apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  finalizers:
  - postgres-operator.crunchydata.com/finalizer
  generation: 1
  name: database
  namespace: db
spec:
  proxy:
        pgBouncer:
                image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.18-0
  userInterface:
    pgAdmin:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-10
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
         - --type=full
      global:
        repo1-retention-full: "30"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
          full: "0 2 * * 0"
          differential: "0 2 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  instances:
  - dataVolumeClaimSpec:
      storageClassName: primary
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    name: "instance-1"
    replicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: storage.type
              operator: In
              values:
              - primary


  port: 5432
  postgresVersion: 14
